orbit:
  a: 1.0
  e: 0.1

grid:
  nz: 30
  ndot: 30
  z0: -2
  z1: 2
  dotz0: -2
  dotz1: 2
  t0: 0.0
  tf: 1000.0

integrator:
  method: "Radau"

plotter:
  rev_min: 10
  zmin: -2.5
  zmax: 2.5
  dotzmin: -2.0
  dotzmax: 2.0
  dpi: 400

parallel:
  track: true

